# Generated by Django 4.1.4 on 2022-12-27 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo1', '0002_projectdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectdata',
            old_name='user_name',
            new_name='username',
        ),
    ]
